sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000040.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000041.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000042.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000043.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000044.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000045.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000046.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000047.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000048.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000049.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000050.jpg /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000040.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000041.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000042.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000043.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000044.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000045.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000046.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000047.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000048.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000049.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images
sudo cp /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511/images/00000050.png /home/data1/difanrui/Project/instant-nsr-pl/data/lung_511_for_debug/images